name: pdf_generator
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  flutter_markdown: ^0.6.14
  image_picker: ^1.0.7

#  edit task 2

  file_picker: ^8.0.0
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_pdf: ^24.1.41
#  path_provider: ^2.1.2
  permission_handler: ^11.0.1

  pdf: ^3.10.4
  # pdf to img
#  flutter_pdf_renderer: ^1.3.0
  image_painter: ^0.5.0
#  path_provider: ^2.0.2
#  pdf: ^3.10.4
#  pdf to img------------
  image: ^4.1.7
  printing: ^5.12.0
#  img edit
  image_editor_plus: ^1.0.0
  flutter_painter: ^1.0.0
  open_filex: ^4.3.2

#  extract text------------------
#  syncfusion_flutter_pdf: ^28.2.5
#  file_picker:
#  path_provider:

#  flutter_pdfview: ^1.3.2
#  syncfusion_flutter_pdf: ^24.1.41
  syncfusion_flutter_pdfviewer: ^24.1.41
#  path_provider: ^2.1.2
#  permission_handler: ^11.0.1

#  file_picker: ^8.0.0  # For picking PDF files
#  flutter_pdfview: ^1.3.2  # For rendering PDFs
  syncfusion_flutter_signaturepad: ^24.2.9
#  syncfusion_flutter_pdf: ^25.1.35  # For modifying and saving PDFs

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  assets:
    - assets/fonts/
  fonts:
      - family: Skranji
        fonts:
          - asset: assets/fonts/Skranji-Regular.ttf
          - asset: assets/fonts/Skranji-Bold.ttf

      - family: Tomorrow
        fonts:
          - asset: assets/fonts/Tomorrow-Regular.ttf
          - asset: assets/fonts/Tomorrow-Bold.ttf

      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
      - family: Lato
        fonts:
          - asset: assets/fonts/Lato-Regular.ttf
          - asset: assets/fonts/Lato-Light.ttf
      - family: Tinos
        fonts:
          - asset: assets/fonts/Tinos-Regular.ttf
          - asset: assets/fonts/Tinos-Bold.ttf

      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Bold.ttf



    #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
